name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Upload vendor folder
        uses: actions/upload-artifact@v4
        with:
          name: vendor
          path: vendor

  tests:
    name: Run Tests
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
          tools: composer
      - name: Download vendor folder
        uses: actions/download-artifact@v4
        with:
          name: vendor
          path: vendor
      - run: XDEBUG_MODE=coverage vendor/bin/phpunit --configuration phpunit.xml tests/AppTest --display-deprecations --display-notices --display-warnings --coverage-text

  static-analysis:
    name: Static Analysis
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Download vendor folder
        uses: actions/download-artifact@v4
        with:
          name: vendor
          path: vendor
      - run: vendor/bin/phpstan analyse src --level 9 --memory-limit 256M
      - run: vendor/bin/phpmd src ansi ruleset.xml

  code-style:
    name: Code Style
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Download vendor folder
        uses: actions/download-artifact@v4
        with:
          name: vendor
          path: vendor
      - run: vendor/bin/phpcs

  security:
    name: Security Check
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Download vendor folder
        uses: actions/download-artifact@v4
        with:
          name: vendor
          path: vendor
      - run: ./local-php-security-checker --no-dev
