name: CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Run PHPUnit with coverage
        run: XDEBUG_MODE=coverage vendor/bin/phpunit --configuration phpunit.xml tests/AppTest --display-deprecations --display-notices --display-warnings --coverage-text

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src --level 9 --memory-limit 256M

      - name: Run PHPMD
        run: vendor/bin/phpmd src ansi ruleset.xml

      - name: Run PHPCS
        run: vendor/bin/phpcs

      - name: Run local-php-security-checker
        run: ./local-php-security-checker --no-dev
